// <auto-generated />
using System;
using HistorialCancha.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HistorialCancha.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(HistorialContext))]
    [Migration("20260812145914_EquiposDePrimera")]
    partial class EquiposDePrimera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_Equipos_Nombre");

                    b.ToTable("Equipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Aldosivi"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Argentinos Juniors"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Atlético Tucumán"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Banfield"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Barracas Central"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Belgrano"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Boca Juniors"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Central Córdoba (SdE)"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "Defensa y Justicia"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Nombre = "Deportivo Riestra"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Nombre = "Estudiantes (LP)"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Nombre = "Gimnasia y Esgrima (LP)"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Nombre = "Godoy Cruz"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Nombre = "Huracán"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Nombre = "Independiente"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Nombre = "Independiente Rivadavia"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Nombre = "Instituto"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Nombre = "Lanús"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Nombre = "Newell's Old Boys"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Nombre = "Platense"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Nombre = "Racing Club"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Nombre = "River Plate"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Nombre = "Rosario Central"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            Nombre = "San Lorenzo"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            Nombre = "San Martín (SJ)"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            Nombre = "Sarmiento"
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            Nombre = "Talleres"
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            Nombre = "Tigre"
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            Nombre = "Unión"
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            Nombre = "Vélez Sarsfield"
                        });
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Condicion")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Estadio")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GolesAFavor")
                        .HasColumnType("int");

                    b.Property<int>("GolesEnContra")
                        .HasColumnType("int");

                    b.Property<string>("Rival")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Torneo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsUnique()
                        .HasDatabaseName("UX_Partidos_Fecha");

                    b.HasIndex("Rival")
                        .HasDatabaseName("IX_Partidos_Rival");

                    b.ToTable("Partidos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Partidos_Condicion", "[Condicion] IN (0, 1)");

                            t.HasCheckConstraint("CK_Partidos_GolesAFavor", "[GolesAFavor] >= 0");

                            t.HasCheckConstraint("CK_Partidos_GolesEnContra", "[GolesEnContra] >= 0");
                        });
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Vivencia", b =>
                {
                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<string>("ConQuien")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("Modalidad")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Nota")
                        .HasColumnType("tinyint");

                    b.Property<string>("Sector")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("PartidoId");

                    b.ToTable("Vivencias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vivencias_Modalidad", "[Modalidad] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Vivencias_Nota", "[Nota] IS NULL OR [Nota] BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Vivencia", b =>
                {
                    b.HasOne("HistorialCancha.Domain.Entidades.Partido", "Partido")
                        .WithOne("Vivencia")
                        .HasForeignKey("HistorialCancha.Domain.Entidades.Vivencia", "PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Partido", b =>
                {
                    b.Navigation("Vivencia");
                });
#pragma warning restore 612, 618
        }
    }
}
