// <auto-generated />
using System;
using HistorialCancha.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HistorialCancha.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(HistorialContext))]
    [Migration("20260806020851_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Condicion")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Estadio")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GolesAFavor")
                        .HasColumnType("int");

                    b.Property<int>("GolesEnContra")
                        .HasColumnType("int");

                    b.Property<string>("Rival")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Torneo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsUnique()
                        .HasDatabaseName("UX_Partidos_Fecha");

                    b.HasIndex("Rival")
                        .HasDatabaseName("IX_Partidos_Rival");

                    b.ToTable("Partidos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Partidos_Condicion", "[Condicion] IN (0, 1)");

                            t.HasCheckConstraint("CK_Partidos_GolesAFavor", "[GolesAFavor] >= 0");

                            t.HasCheckConstraint("CK_Partidos_GolesEnContra", "[GolesEnContra] >= 0");
                        });
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Vivencia", b =>
                {
                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<string>("ConQuien")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("Modalidad")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Nota")
                        .HasColumnType("tinyint");

                    b.Property<string>("Sector")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("PartidoId");

                    b.ToTable("Vivencias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vivencias_Modalidad", "[Modalidad] BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Vivencias_Nota", "[Nota] IS NULL OR [Nota] BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Vivencia", b =>
                {
                    b.HasOne("HistorialCancha.Domain.Entidades.Partido", "Partido")
                        .WithOne("Vivencia")
                        .HasForeignKey("HistorialCancha.Domain.Entidades.Vivencia", "PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Partido", b =>
                {
                    b.Navigation("Vivencia");
                });
#pragma warning restore 612, 618
        }
    }
}
