// <auto-generated />
using System;
using HistorialCancha.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HistorialCancha.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(HistorialContext))]
    [Migration("20260819174315_AutenticacionUsuarios")]
    partial class AutenticacionUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("Condicion")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estadio")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GolesAFavor")
                        .HasColumnType("integer");

                    b.Property<int>("GolesEnContra")
                        .HasColumnType("integer");

                    b.Property<string>("Rival")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Torneo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Rival")
                        .HasDatabaseName("IX_Partidos_Rival");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("UX_Partidos_Usuario_Fecha");

                    b.ToTable("Partidos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Partidos_Condicion", "\"Condicion\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Partidos_GolesAFavor", "\"GolesAFavor\" >= 0");

                            t.HasCheckConstraint("CK_Partidos_GolesEnContra", "\"GolesEnContra\" >= 0");
                        });
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("UX_Usuarios_Dni");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Vivencia", b =>
                {
                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<string>("ConQuien")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<byte>("Modalidad")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Nota")
                        .HasColumnType("smallint");

                    b.Property<string>("Sector")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("PartidoId");

                    b.ToTable("Vivencias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vivencias_Modalidad", "\"Modalidad\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Vivencias_Nota", "\"Nota\" IS NULL OR \"Nota\" BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Partido", b =>
                {
                    b.HasOne("HistorialCancha.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Vivencia", b =>
                {
                    b.HasOne("HistorialCancha.Domain.Entidades.Partido", "Partido")
                        .WithOne("Vivencia")
                        .HasForeignKey("HistorialCancha.Domain.Entidades.Vivencia", "PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("HistorialCancha.Domain.Entidades.Partido", b =>
                {
                    b.Navigation("Vivencia");
                });
#pragma warning restore 612, 618
        }
    }
}
